import type {INodeProperties} from 'n8n-workflow';

export const avaliacaoDesempenhoConfig: INodeProperties[] = [

    // ─── listAvaliacaoDesempenho ──────────────────────────────────────────────
    {
        displayName: 'ID SGP da Matrícula',
        name: 'id_sgp_matricula',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP da matrícula',
        displayOptions: {show: {endpoints: ['listAvaliacaoDesempenho']}},
    },
    {
        displayName: 'ID SGP do Componente Curricular',
        name: 'id_sgp_componente_curricular',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP do componente curricular da instituição',
        displayOptions: {show: {endpoints: ['listAvaliacaoDesempenho']}},
    },
    {
        displayName: 'ID SGP da Turma',
        name: 'id_sgp_turma',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP da turma — filtra avaliações dos alunos dessa turma',
        displayOptions: {show: {endpoints: ['listAvaliacaoDesempenho']}},
    },
    {
        displayName: 'Área de Conhecimento',
        name: 'co_area_conhecimento',
        type: 'options',
        default: '',
        required: false,
        description: 'Área de conhecimento do componente curricular',
        options: [
            {name: 'Todas', value: ''},
            {name: 'Linguagens - (1)', value: 1},
            {name: 'Matemática - (2)', value: 2},
            {name: 'Ciências da Natureza - (3)', value: 3},
            {name: 'Ciências Humanas e Sociais - (4)', value: 4},
            {name: 'Outras Áreas - (99)', value: 99},
        ],
        displayOptions: {show: {endpoints: ['listAvaliacaoDesempenho']}},
    },
    {
        displayName: 'Ano Letivo da Matrícula',
        name: 'nu_ano_matricula',
        type: 'number',
        default: new Date().getFullYear(),
        required: false,
        description: 'Ano letivo da matrícula, ex: 2024',
        typeOptions: {minValue: 2024, maxValue: new Date().getFullYear()},
        displayOptions: {show: {endpoints: ['listAvaliacaoDesempenho']}},
    },
    {
        displayName: 'Etapa de Ensino',
        name: 'co_etapa_ensino',
        type: 'options',
        default: '',
        required: false,
        description: 'Etapa de ensino da matrícula',
        options: [
            {name: 'Todas', value: ''},
            {name: 'Educação Infantil - Creche (0 a 3 anos) - (1)', value: 1},
            {name: 'Educação Infantil - Pré-escola (4 e 5 anos) - (2)', value: 2},
            {name: 'Educação Infantil - Unificada (0 a 5 anos) - (3)', value: 3},
            {name: 'Ensino Fundamental 9 anos - 1º ano - (14)', value: 14},
            {name: 'Ensino Fundamental 9 anos - 2º ano - (15)', value: 15},
            {name: 'Ensino Fundamental 9 anos - 3º ano - (16)', value: 16},
            {name: 'Ensino Fundamental 9 anos - 4º ano - (17)', value: 17},
            {name: 'Ensino Fundamental 9 anos - 5º ano - (18)', value: 18},
            {name: 'Ensino Fundamental 9 anos - 6º ano - (19)', value: 19},
            {name: 'Ensino Fundamental 9 anos - 7º ano - (20)', value: 20},
            {name: 'Ensino Fundamental 9 anos - 8º ano - (21)', value: 21},
            {name: 'Ensino Fundamental 9 anos - 9º ano - (41)', value: 41},
            {name: 'Ensino Fundamental 9 anos - Multi - (22)', value: 22},
            {name: 'Ensino Fundamental 9 anos - Correção de Fluxo - (23)', value: 23},
            {name: 'Educação Infantil e Ensino Fundamental Multietapa - (56)', value: 56},
            {name: 'Ensino Médio - 1ª série - (25)', value: 25},
            {name: 'Ensino Médio - 2ª série - (26)', value: 26},
            {name: 'Ensino Médio - 3ª série - (27)', value: 27},
            {name: 'Ensino Médio - 4ª série - (28)', value: 28},
            {name: 'Ensino Médio - Não seriada - (29)', value: 29},
            {name: 'Ensino Médio Normal/Magistério - 1ª série - (35)', value: 35},
            {name: 'Ensino Médio Normal/Magistério - 2ª série - (36)', value: 36},
            {name: 'Ensino Médio Normal/Magistério - 3ª série - (37)', value: 37},
            {name: 'Ensino Médio Normal/Magistério - 4ª série - (38)', value: 38},
            {name: 'EJA - Ensino Fundamental - Anos Iniciais (1º segmento) - (69)', value: 69},
            {name: 'EJA - Ensino Fundamental - Anos Finais (2º segmento) - (70)', value: 70},
            {name: 'EJA - Ensino Fundamental - Anos Iniciais e Finais (Multietapas) - (72)', value: 72},
            {name: 'EJA - Ensino Médio (3º segmento) - (71)', value: 71},
            {name: 'EJA - Curso FIC Integrado - Nível Fundamental - (73)', value: 73},
            {name: 'EJA - Curso FIC Integrado - Nível Médio - (67)', value: 67},
            {name: 'EJA - Curso Técnico Integrado - (74)', value: 74},
            {name: 'Curso Técnico - Concomitante - (39)', value: 39},
            {name: 'Curso Técnico - Subsequente - (40)', value: 40},
            {name: 'Educação Profissional Mista / Curso Técnico Misto - (64)', value: 64},
            {name: 'Curso FIC Concomitante - (68)', value: 68},
            {name: 'Não aplicável (AEE / Atividade Complementar) - (0)', value: 0},
        ],
        displayOptions: {show: {endpoints: ['listAvaliacaoDesempenho']}},
    },
    {
        displayName: 'Página',
        name: 'page',
        type: 'number',
        default: 1,
        required: false,
        description: 'Número da página',
        typeOptions: {minValue: 1},
        displayOptions: {show: {endpoints: ['listAvaliacaoDesempenho']}},
    },
    {
        displayName: 'Itens por Página',
        name: 'page_size',
        type: 'number',
        default: 100,
        required: false,
        description: 'Itens por página (padrão: 100, máximo: 5000)',
        typeOptions: {minValue: 1, maxValue: 5000},
        displayOptions: {show: {endpoints: ['listAvaliacaoDesempenho']}},
    },

    // ─── createAvaliacaoDesempenhoLote ────────────────────────────────────────
    {
        displayName: 'Avaliações (JSON)',
        name: 'avaliacoes_cadastro_json',
        type: 'json',
        default: '[]',
        required: true,
        description: 'Array de avaliações de desempenho a cadastrar. Campos obrigatórios: id_sgp_estudante, estudante_cpf, estudante_nome, id_sgp_matricula, estudante_apoio_pedagogico, co_entidade, no_entidade, estudante_etapa_de_ensino, nu_ano_matricula, id_sgp_componente_curricular, co_componente_curricular_area_conhecimento, co_componente_curricular, sistema_avaliacao_desempenho, desempenho_estudante_componente_curricular',
        displayOptions: {show: {endpoints: ['createAvaliacaoDesempenhoLote']}},
    },

    // ─── editAvaliacaoDesempenhoLote ──────────────────────────────────────────
    {
        displayName: 'Avaliações (JSON)',
        name: 'avaliacoes_edicao_json',
        type: 'json',
        default: '[]',
        required: true,
        description: 'Array de avaliações de desempenho a editar. Cada item deve conter editar_avaliacao=1 além dos campos obrigatórios do cadastro',
        displayOptions: {show: {endpoints: ['editAvaliacaoDesempenhoLote']}},
    },
];