import type {INodeProperties} from 'n8n-workflow';

export const estudantesConfig: INodeProperties[] = [

    // ─── listEstudantes ───────────────────────────────────────────────────────
    {
        displayName: 'ID SGP da Instituição',
        name: 'id_sgp_instituicao',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP da instituição',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'ID SGP da Turma',
        name: 'id_sgp_turma',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP da turma',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'CPF do Estudante',
        name: 'estudante_cpf',
        type: 'string',
        default: '',
        required: false,
        description: 'CPF do estudante',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Código INEP da Instituição',
        name: 'co_entidade',
        type: 'string',
        default: '',
        required: false,
        description: 'Código INEP da instituição de ensino',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Ano de Matrícula',
        name: 'ano_matricula',
        type: 'number',
        default: new Date().getFullYear(),
        required: false,
        typeOptions: {minValue: 2024, maxValue: new Date().getFullYear()},
        description: 'Ano de referência da matrícula, ex: 2026',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'ID SGP da Matrícula',
        name: 'id_sgp_matricula',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP da matrícula',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Situações da Matrícula',
        name: 'situacoes_matricula',
        type: 'multiOptions',
        default: [],
        required: false,
        description: 'Filtra por situações da matrícula. Quando não informado, retorna apenas ativas (situação=0)',
        options: [
            {name: 'Em Andamento - (0)', value: 0},
            {name: 'Informação Incorreta - (1)', value: 1},
            {name: 'Transferência - Mesma Rede - (2)', value: 2},
            {name: 'Transferência - Outra Rede Pública - (3)', value: 3},
            {name: 'Transferência - Rede Privada - (4)', value: 4},
            {name: 'Transferência - Rede Não Identificada - (5)', value: 5},
            {name: 'Evasão - (6)', value: 6},
            {name: 'Abandono - (7)', value: 7},
            {name: 'Óbito Informado - (8)', value: 8},
            {name: 'Reclassificação - (9)', value: 9},
            {name: 'Aprovado - (10)', value: 10},
            {name: 'Concluinte - (11)', value: 11},
            {name: 'Reprovado - (12)', value: 12},
            {name: 'Transferência entre modalidades (EM <> EJA) - (21)', value: 21},
            {name: 'Trancamento de matrícula em curso técnico - (22)', value: 22},
        ],
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Etapas de Ensino',
        name: 'etapas_ensino',
        type: 'multiOptions',
        default: [],
        required: false,
        description: 'Filtra por etapas de ensino. Deixe vazio para retornar todas',
        options: [
            {name: 'Educação Infantil - Creche (0 a 3 anos) - (1)', value: 1},
            {name: 'Educação Infantil - Pré-escola (4 e 5 anos) - (2)', value: 2},
            {name: 'Educação Infantil - Unificada (0 a 5 anos) - (3)', value: 3},
            {name: 'Ensino Fundamental 9 anos - 1º ano - (14)', value: 14},
            {name: 'Ensino Fundamental 9 anos - 2º ano - (15)', value: 15},
            {name: 'Ensino Fundamental 9 anos - 3º ano - (16)', value: 16},
            {name: 'Ensino Fundamental 9 anos - 4º ano - (17)', value: 17},
            {name: 'Ensino Fundamental 9 anos - 5º ano - (18)', value: 18},
            {name: 'Ensino Fundamental 9 anos - 6º ano - (19)', value: 19},
            {name: 'Ensino Fundamental 9 anos - 7º ano - (20)', value: 20},
            {name: 'Ensino Fundamental 9 anos - 8º ano - (21)', value: 21},
            {name: 'Ensino Fundamental 9 anos - 9º ano - (41)', value: 41},
            {name: 'Ensino Fundamental 9 anos - Multi - (22)', value: 22},
            {name: 'Ensino Fundamental 9 anos - Correção de Fluxo - (23)', value: 23},
            {name: 'Educação Infantil e Ensino Fundamental Multietapa - (56)', value: 56},
            {name: 'Ensino Médio - 1ª série - (25)', value: 25},
            {name: 'Ensino Médio - 2ª série - (26)', value: 26},
            {name: 'Ensino Médio - 3ª série - (27)', value: 27},
            {name: 'Ensino Médio - 4ª série - (28)', value: 28},
            {name: 'Ensino Médio - Não seriada - (29)', value: 29},
            {name: 'Ensino Médio Normal/Magistério - 1ª série - (35)', value: 35},
            {name: 'Ensino Médio Normal/Magistério - 2ª série - (36)', value: 36},
            {name: 'Ensino Médio Normal/Magistério - 3ª série - (37)', value: 37},
            {name: 'Ensino Médio Normal/Magistério - 4ª série - (38)', value: 38},
            {name: 'EJA - Ensino Fundamental - Anos Iniciais (1º segmento) - (69)', value: 69},
            {name: 'EJA - Ensino Fundamental - Anos Finais (2º segmento) - (70)', value: 70},
            {name: 'EJA - Ensino Fundamental - Anos Iniciais e Finais (Multietapas) - (72)', value: 72},
            {name: 'EJA - Ensino Médio (3º segmento) - (71)', value: 71},
            {name: 'EJA - Curso FIC Integrado - Nível Fundamental - (73)', value: 73},
            {name: 'EJA - Curso FIC Integrado - Nível Médio - (67)', value: 67},
            {name: 'EJA - Curso Técnico Integrado - (74)', value: 74},
            {name: 'Curso Técnico - Concomitante - (39)', value: 39},
            {name: 'Curso Técnico - Subsequente - (40)', value: 40},
            {name: 'Educação Profissional Mista / Curso Técnico Misto - (64)', value: 64},
            {name: 'Curso FIC Concomitante - (68)', value: 68},
            {name: 'Não aplicável (AEE / Atividade Complementar) - (0)', value: 0},
        ],
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Incluir Outras Matrículas',
        name: 'outras_matriculas',
        type: 'boolean',
        default: false,
        required: false,
        description: 'Whether inclui matrículas ativas do estudante em outras redes. Retorna apenas estudantes com vínculos em múltiplas redes',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Incluir Endereço',
        name: 'include_endereco',
        type: 'boolean',
        default: false,
        required: false,
        description: 'Whether inclui dados de endereço (logradouro, CEP, coordenadas)',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Página',
        name: 'page',
        type: 'number',
        default: 1,
        required: false,
        description: 'Número da página',
        typeOptions: {minValue: 1},
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Itens por Página',
        name: 'page_size',
        type: 'number',
        default: 100,
        required: false,
        description: 'Itens por página (padrão: 100, máximo: 5000)',
        typeOptions: {minValue: 1, maxValue: 5000},
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },

    // ─── createEstudantesSemTurmaLote ─────────────────────────────────────────
    {
        displayName: 'Estudantes (JSON)',
        name: 'estudantes_sem_turma_json',
        type: 'json',
        default: '[]',
        required: true,
        description: 'Array de estudantes a cadastrar sem turma. Consulte a documentação para os campos obrigatórios',
        displayOptions: {show: {endpoints: ['createEstudantesSemTurmaLote']}},
    },

    // ─── createEstudantesComTurmaLote ─────────────────────────────────────────
    {
        displayName: 'Estudantes (JSON)',
        name: 'estudantes_com_turma_json',
        type: 'json',
        default: '[]',
        required: true,
        description: 'Array de estudantes a cadastrar com turma. Consulte a documentação para os campos obrigatórios',
        displayOptions: {show: {endpoints: ['createEstudantesComTurmaLote']}},
    },

    // ─── editEstudantesLote ───────────────────────────────────────────────────
    {
        displayName: 'Estudantes (JSON)',
        name: 'estudantes_edicao_json',
        type: 'json',
        default: '[]',
        required: true,
        description: 'Array de estudantes a editar. Cada item deve conter id_sgp_estudante e editar_dados=1',
        displayOptions: {show: {endpoints: ['editEstudantesLote']}},
    },
];