import type {INodeProperties} from 'n8n-workflow';

export const estudantesConfig: INodeProperties[] = [

    // ─── listEstudantes ───────────────────────────────────────────────────────
    {
        displayName: 'ID SGP da Instituição',
        name: 'id_sgp_instituicao',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP da instituição',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'ID SGP da Turma',
        name: 'id_sgp_turma',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP da turma',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'CPF do Estudante',
        name: 'estudante_cpf',
        type: 'string',
        default: '',
        required: false,
        description: 'CPF do estudante',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Código INEP da Instituição',
        name: 'co_entidade',
        type: 'string',
        default: '',
        required: false,
        description: 'Código INEP da instituição de ensino',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Ano de Matrícula',
        name: 'ano_matricula',
        type: 'number',
        default: new Date().getFullYear(),
        required: false,
        typeOptions: {minValue: 2024, maxValue: new Date().getFullYear()},
        description: 'Ano de referência da matrícula, ex: 2026',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'ID SGP da Matrícula',
        name: 'id_sgp_matricula',
        type: 'number',
        default: null,
        required: false,
        description: 'ID SGP da matrícula',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Situações da Matrícula',
        name: 'situacoes_matricula',
        type: 'string',
        default: '',
        required: false,
        description: 'Códigos de situação separados por vírgula. Ex: 2,3. Quando não informado, retorna apenas ativas (situação=0)',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Etapas de Ensino',
        name: 'etapas_ensino',
        type: 'string',
        default: '',
        required: false,
        description: 'Etapas de ensino separadas por vírgula. Ex: 25,26,27',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Incluir Outras Matrículas',
        name: 'outras_matriculas',
        type: 'boolean',
        default: false,
        required: false,
        description: 'Whether inclui matrículas ativas do estudante em outras redes. Retorna apenas estudantes com vínculos em múltiplas redes',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Incluir Endereço',
        name: 'include_endereco',
        type: 'boolean',
        default: false,
        required: false,
        description: 'Whether inclui dados de endereço (logradouro, CEP, coordenadas)',
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Página',
        name: 'page',
        type: 'number',
        default: 1,
        required: false,
        description: 'Número da página',
        typeOptions: {minValue: 1},
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },
    {
        displayName: 'Itens por Página',
        name: 'page_size',
        type: 'number',
        default: 100,
        required: false,
        description: 'Itens por página (padrão: 100, máximo: 5000)',
        typeOptions: {minValue: 1, maxValue: 5000},
        displayOptions: {show: {endpoints: ['listEstudantes']}},
    },

    // ─── createEstudantesSemTurmaLote ─────────────────────────────────────────
    {
        displayName: 'Estudantes (JSON)',
        name: 'estudantes_sem_turma_json',
        type: 'json',
        default: '[]',
        required: true,
        description: 'Array de estudantes a cadastrar sem turma. Consulte a documentação para os campos obrigatórios',
        displayOptions: {show: {endpoints: ['createEstudantesSemTurmaLote']}},
    },

    // ─── createEstudantesComTurmaLote ─────────────────────────────────────────
    {
        displayName: 'Estudantes (JSON)',
        name: 'estudantes_com_turma_json',
        type: 'json',
        default: '[]',
        required: true,
        description: 'Array de estudantes a cadastrar com turma. Consulte a documentação para os campos obrigatórios',
        displayOptions: {show: {endpoints: ['createEstudantesComTurmaLote']}},
    },

    // ─── editEstudantesLote ───────────────────────────────────────────────────
    {
        displayName: 'Estudantes (JSON)',
        name: 'estudantes_edicao_json',
        type: 'json',
        default: '[]',
        required: true,
        description: 'Array de estudantes a editar. Cada item deve conter id_sgp_estudante e editar_dados=1',
        displayOptions: {show: {endpoints: ['editEstudantesLote']}},
    },
];